# MCU / ボード設定
MCU = RP2040
BOARD = GENERIC_RP2040
BOOTLOADER = rp2040

# QMK 機能
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
