name: Build Vial Firmware

on:
  push:
    branches: [ cleanup-keybords ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

env:
      UV_PYTHON: "3.12"
      
    steps:
      - uses: actions/checkout@v4

      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Build Vial firmware
        uses: ./actions/build-vial
        with:
          keyboard: olthotenkey
          keymap: vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: vial-firmware
          path: output/
